---
- hosts: localhost
  gather_facts: no
  become: no

  tasks:
    - name: execute command
      command:
        cmd: 'cat script/playout_failed.txt'
      register: result
      changed_when: false

    - name: output result
      debug:
        msg: "{{ result.stdout_lines }}"
